swagger: "2.0"
info:
  title: Chaos API
  description: description for the Chaos API.
  version: 1.0.0
host: 217.69.8.253
basePath: /
schemes:
  - http
paths:
  /chaos:
    get:
      summary: bleh
      description: Optional extended description in Markdown.
      produces:
        - text/plain
      parameters:
        - in: query
          name: failure_code
          required: false
          type: integer
          minimum: 1
          description: status code to generate upon failure
        - in: query
          name: failure_rate
          required: false
          type: integer
          minimum: 1
          maximum: 100
          description: failure rate in percentage of queries
        - in: query
          name: cpu_cost
          required: false
          type: integer
          minimum: 1
          description: CPU cost of the call in number of operations
        - in: query
          name: cpu_cost_delta
          required: false
          type: integer
          minimum: 1
          description: CPU cost variation of the call in number of operations
        - in: query
          name: mem_cost
          required: false
          type: integer
          minimum: 1
          description: Memory cost of the call in bytes
        - in: query
          name: mem_cost_delta
          required: false
          type: integer
          minimum: 1
          description: Memory cost variation of the call in bytes
        - in: query
          name: time_cost
          required: false
          type: float
          minimum: 1
          description: Time cost of the call in seconds
        - in: query
          name: time_cost_delta
          required: false
          type: float
          minimum: 1
          description: Time cost variation of the call in seconds
        - in: query
          name: disk_read_cost
          required: false
          type: integer
          minimum: 1
          description: Disk read cost of the call in bytes
        - in: query
          name: disk_read_cost_delta
          required: false
          type: integer
          minimum: 1
          description: Disk read cost variation of the call in bytes
        - in: query
          name: disk_write_cost
          required: false
          type: integer
          minimum: 1
          description: Disk write cost of the call in bytes
        - in: query
          name: disk_write_cost_delta
          required: false
          type: integer
          minimum: 1
          description: Disk write cost variation of the call in bytes
        - in: query
          name: io_read_cost
          required: false
          type: integer
          minimum: 1
          description: IO read cost of the call in bytes
        - in: query
          name: io_read_cost_delta
          required: false
          type: integer
          minimum: 1
          description: IO read cost variation of the call in bytes
        - in: query
          name: io_write_cost
          required: false
          type: integer
          minimum: 1
          description: IO write cost of the call in bytes
        - in: query
          name: io_write_cost_delta
          required: false
          type: integer
          minimum: 1
          description: IO write cost variation of the call in bytes
      responses:
        200:
          description: OK
